name: todo

on:
  push:
    branches: [master,main]

jobs:
  todo:
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v3
      -
        name: Check Todos
        uses: ribtoks/tdg-github-action@4eecdffb1ec35174b71c84e825d581686a9be1e1
        with:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
          SHA: ${{ github.sha }}
          REF: ${{ github.ref }}